### ISSUE TITLE
[question] Can this be used independently of "Netlify Graph"?

### ISSUE THREAD

**Issue by ClaytonFarr** [netlify/netlify-graph-auth#2]
Trying to understand how this project may fit into or alongside - https://github.com/netlify/labs/blob/main/features/graph/documentation/authentication.md

Is it possible to use this functionality (and its larger list of providers) to try out OneGraph's functionality earlier? 

Or is this a supporting piece of Netlify Graph that's meant to be consumed indirectly?

**Comment by sgrove** [comment]
We'll be releasing documentation on this soon - it's meant to be used for client-side authentication (e.g. having your _users_ log into Spotify) rather than you as the main developer provisioning a server-side auth token.

@localden will update this issue once we have the documentation in place!

**Comment by ClaytonFarr** [comment]
Thanks @sgrove
